spring:
  application:
    name: match-manager
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/soccer_match}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:12345678}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder:
              TRACE