spring:
  application:
    name: match-manager
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/soccer-match}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:12345678}
#server:
#  error:
#    include-stacktrace: never